export * from './about';
export * from './chart';
export * from './contact';
export * from './faq';
export * from './footer';
export * from './hero-slider';
export * from './map-view';
export * from './navbar';
export * from './partners';
